# he6_cres_spec_sims example config file. 

Daq:
  spec_length: .035
  freq_bw: 1.2e+9
  freq_bins: 4096
  roach_avg: 2
  requant_gain: 20
  base_gain: 1.0e+11  # 1.0e+11 seemed good.
  rng_seed: 123456
  build_labels: True
  waveguide_side": "I"
  gain_noise_csv_path: "/Users/winston/Documents/dsir-1031/projects/he6-cres-deep-learning/demo/gain_noise/base_gain_noise.csv"
  spec_prefix: "test"